name: dev_flutter_test_example
description: Example using dev_flutter_test
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  dev_flutter_test:
    path: ../../dev_flutter_test
  cupertino_icons:
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
resolution: workspace
