name: dev_flutter_test_repo_support
description: Dev flutter test repo (tools)
version: 0.2.0
publish_to: none

environment:
  sdk: ^3.7.0

dev_dependencies:
  path: ">=1.9.0"
  pub_semver: ">=2.1.4"
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.9.8'
  tekartik_travis_ci_flutter:
    git:
      url: https://github.com/tekartik/travis_ci_flutter.dart
      ref: dart3a
    version: '>=0.1.0'
  test: ">=1.24.0"
  dev_build: ">=1.1.2"


